use_frameworks!

platform :ios, '8.0'

target 'CodeCovExample_Example' do
  pod 'CodeCovExample', :path => '../'

  target 'CodeCovExample_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
