# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Tests SDK via Specta"
  lane :unit_tests_pod do
      cocoapods(use_bundle_exec: false)
      run_tests(
          workspace: "CodeCovExample.xcworkspace",
          scheme: "CodeCovExample_Tests",
          devices: [
              'iPhone 11',
              'iPad Pro (11-inch) (2nd generation)'
          ],
          code_coverage: true,
          derived_data_path: "./fastlane/build",
          configuration: 'Debug'
      )
  end
  lane :ui_tests_pod do
      cocoapods(use_bundle_exec: false)
      run_tests(
          workspace: "CodeCovExample.xcworkspace",
          scheme: "CodeCovExample_ExampleUITests",
          devices: [
              'iPhone 11',
              'iPad Pro (11-inch) (2nd generation)'
          ],
          code_coverage: true,
          derived_data_path: "./fastlane/build",
          configuration: 'Debug'
      )
  end
end
