# This is a basic workflow to help you get started with Actions

name: Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        cd Example
        gem install bundler:1.17.2
        bundle install
        bundle exec fastlane unit_tests_pod

    # Runs a set of commands using the runners shell
    - name: Upload coverage report
      run: |
        cd Example/fastlane
        xcrun xccov view --report --json build/Logs/Test/Run-CodeCovExample_Tests-****.**.**_**-**-**-+****.xcresult > result.json
        ./xcc generate result.json . cobertura-xml --verbose
        sed -e 's/<tab>/<space>/g' cobertura.xml > coverage.xml
        bash <(curl -s https://codecov.io/bash) -f coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
